name: Build

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Extract Version from .csproj
        id: extract_version
        run: |
          version=$(xmllint --xpath "string(//Project/PropertyGroup/Version)" Bloodcraft.csproj)
          echo "##[set-output name=version;]$version"
          
      - name: Update manifest.json
        run: |
          version=${{ steps.extract_version.outputs.version }}
          jq --arg version "$version" '.version_number = $version' manifest.json > temp.json && mv temp.json manifest.json
          
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          additionalArguments: '/updateprojectfiles /overrideconfig "mode=Mainline"'

      - name: Build (Release)
        run: dotnet build . --configuration Release -p:Version=${{ steps.extract_version.outputs.version }}

      - name: GH Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'workflow_dispatch'
        with:
          body: Manual pre-release of ${{ steps.extract_version.outputs.version }} for ${{ env.GitVersion_ShortSha }}
          name: v${{ steps.extract_version.outputs.version }}
          fail_on_unmatched_files: true
          prerelease: true
          tag_name: v${{ steps.extract_version.outputs.version }}
          files: |
            Bloodcraft.dll
            manifest.json
            CHANGELOG.md
            README.md
            icon.png
