name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        description: The tag to release.
        type: string

jobs:
  release_on_thunderstore:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
          dotnet-quality: 'preview'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Version from .csproj
        id: extract_version
        run: |
          version=$(xmllint --xpath "string(//Project/PropertyGroup/Version)" Bloodcraft.csproj)
          echo "##[set-output name=version;]$version"
        shell: bash

      - name: Set Release Tag
        run: echo "RELEASE_TAG=v${{ steps.extract_version.outputs.version }}" >> $GITHUB_ENV

      - name: Download Release
        run: gh release download ${{ env.RELEASE_TAG }} -D ./dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Thunderstore CLI (tcli)
        run: dotnet tool install --global tcli

      - name: Prepare Thunderstore Package
        run: |
          version=${{ steps.extract_version.outputs.version }}
          mkdir -p ./dist/package
          cp Bloodcraft.dll manifest.json CHANGELOG.md README.md icon.png ./dist/package/
          cd ./dist/package
          zip -r ../zfolmt-Bloodcraft-$version.zip .
        shell: bash

      - name: Publish build to Thunderstore
        run: tcli publish --token ${{ secrets.THUNDERSTORE_KEY }} --package-version ${{ env.RELEASE_TAG:1 }} --config ./dist/thunderstore.toml
